"""Lexicon module for the Kirkham Grammar Parser.

This module contains the word lists and vocabulary used for part-of-speech
classification and grammar analysis.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Lexicon:
    """Pluggable lexicon containing word lists for classification.

    Follows the vocabulary organization from Kirkham's Grammar.
    Users can extend or customize lexicons by creating a new instance:

    Example:
        custom_lex = Lexicon(
            transitive_verbs=Lexicon.DEFAULT_TRANSITIVE_VERBS | {"customize"},
        )
        parser = Parser(lexicon=custom_lex)

    Note: Using frozenset for immutable word lists provides micro-optimization
    for membership testing (O(1) lookup with slightly better cache performance).

    """

    # Default lexicon values (class-level constants for reference)
    DEFAULT_ARTICLES: frozenset[str] = frozenset({"the", "a", "an"})

    PERSONAL_PRONOUNS: set[str] = frozenset(
        {
            # personal
            "i",
            "you",
            "he",
            "she",
            "it",
            "we",
            "they",
            "me",
            "him",
            "her",
            "us",
            "them",
            "thou",
            "thee",
            "ye",
            # reflexive/intensive
            "myself",
            "yourself",
            "himself",
            "herself",
            "itself",
            "ourselves",
            "yourselves",
            "themselves",
        }
    )

    POSSESSIVE_PRONOUNS: set[str] = frozenset(
        {
            "my",
            "thy",
            "your",
            "his",
            "her",
            "its",
            "our",
            "their",
            "mine",
            "thine",
            "yours",
            "hers",
            "ours",
            "theirs",
            # determiners sometimes used pronominally
            "whose",
        }
    )

    DEMONSTRATIVE_PRONOUNS: set[str] = frozenset(
        {"this", "that", "these", "those", "such"}
    )

    RELATIVE_PRONOUNS: set[str] = frozenset(
        {
            "who",
            "whom",
            "whose",
            "which",
            "that",
            "what",
            "whoever",
            "whomever",
            "whichever",
            "whatever",
            "whomsoever",
            "whosoever",
        }
    )

    INTERROGATIVE_PRONOUNS: set[str] = frozenset(
        {
            "who",
            "whom",
            "whose",
            "which",
            "what",
            "whoever",
            "whomever",
            "whichever",
            "whatever",
        }
    )

    COORDINATING_CONJUNCTIONS: set[str] = frozenset(
        {"and", "or", "but", "nor", "for", "yet", "so", "either", "neither", "both"}
    )

    SUBORDINATING_CONJUNCTIONS: set[str] = frozenset(
        {
            "after",
            "although",
            "as",
            "because",
            "before",
            "if",
            "since",
            "than",
            "that",
            "though",
            "unless",
            "until",
            "when",
            "where",
            "whether",
            "while",
            # additions
            "lest",
            "once",
            "whilst",
            "wherever",
            "whenever",
            "whereas",
            "provided",
            "providedthat",
            "inasmuchas",
            "inasmuch",
            "eventhough",
            "evenif",
            "so",
            "sothat",
            "asif",
            "asthough",
            "insofaras",
        }
    )

    PREPOSITIONS: set[str] = frozenset(
        {
            "of",
            "to",
            "in",
            "for",
            "on",
            "with",
            "at",
            "from",
            "by",
            "about",
            "as",
            "into",
            "like",
            "through",
            "after",
            "over",
            "between",
            "out",
            "against",
            "during",
            "without",
            "before",
            "under",
            "around",
            "among",
            "beneath",
            "beside",
            "beyond",
            "near",
            "above",
            "below",
            "across",
            "behind",
            "within",
            # additions
            "aboard",
            "abreast",
            "absent",
            "afterward",
            "aft",
            "along",
            "alongside",
            "amid",
            "amidst",
            "amongst",
            "apud",
            "aslant",
            "astride",
            "atop",
            "bar",
            "barring",
            "besides",
            "betwixt",
            "circa",
            "concerning",
            "considering",
            "despite",
            "down",
            "except",
            "excluding",
            "failing",
            "following",
            "inside",
            "outside",
            "minus",
            "notwithstanding",
            "off",
            "onto",
            "opposite",
            "outof",
            "past",
            "per",
            "plus",
            "regarding",
            "round",
            "save",
            "since",
            "throughout",
            "till",
            "toward",
            "towards",
            "underneath",
            "unlike",
            "until",
            "unto",
            "up",
            "upon",
            "versus",
            "via",
        }
    )

    AUXILIARY_BE: set[str] = frozenset(
        {"am", "is", "are", "was", "were", "be", "been", "being"}
    )

    AUXILIARY_HAVE: set[str] = frozenset({"have", "has", "had", "having"})

    AUXILIARY_DO: set[str] = frozenset({"do", "does", "did"})

    # Get-passive auxiliary (for get-passive constructions like "got caught")
    AUXILIARY_GET: set[str] = frozenset({"get", "gets", "got", "getting", "gotten"})

    MODAL_VERBS: set[str] = frozenset(
        {
            "may",
            "might",
            "can",
            "could",
            "shall",
            "should",
            "will",
            "would",
            "must",
            "ought",
            # marginal/semi-modals (often behave modally)
            "need",
            "dare",
            "usedto",
            "hadbetter",
            "wouldrather",
        }
    )

    COMMON_TRANSITIVE_VERBS: set[str] = frozenset(
        {
            # core (existing)
            "see",
            "sees",
            "saw",
            "seen",
            "know",
            "knows",
            "knew",
            "known",
            "make",
            "makes",
            "made",
            "take",
            "takes",
            "took",
            "taken",
            "give",
            "gives",
            "gave",
            "given",
            "find",
            "finds",
            "found",
            "tell",
            "tells",
            "told",
            "call",
            "calls",
            "called",
            "ask",
            "asks",
            "asked",
            "use",
            "uses",
            "used",
            "write",
            "writes",
            "wrote",
            "written",
            "love",
            "loves",
            "loved",
            "help",
            "helps",
            "helped",
            "build",
            "builds",
            "built",
            "read",
            "reads",
            "buy",
            "buys",
            "bought",
            "sell",
            "sells",
            "sold",
            "show",
            "shows",
            "showed",
            "shown",
            "bring",
            "brings",
            "brought",
            "send",
            "sends",
            "sent",
            # additions (regular forms often include base/3sg/past)
            "accept",
            "accepts",
            "accepted",
            "allow",
            "allows",
            "allowed",
            "answer",
            "answers",
            "answered",
            "appoint",
            "appoints",
            "appointed",
            "approve",
            "approves",
            "approved",
            "arrange",
            "arranges",
            "arranged",
            "beat",
            "beats",
            "beaten",
            "become",  # can be copular; included for coverage
            "beg",
            "begs",
            "begged",
            "believe",
            "believes",
            "believed",
            "borrow",
            "borrows",
            "borrowed",
            "break",
            "breaks",
            "broke",
            "broken",
            "carry",
            "carries",
            "carried",
            "catch",
            "catches",
            "caught",
            "choose",
            "chooses",
            "chose",
            "chosen",
            "clean",
            "cleans",
            "cleaned",
            "close",
            "closes",
            "closed",
            "collect",
            "collects",
            "collected",
            "compare",
            "compares",
            "compared",
            "consider",
            "considers",
            "considered",
            "contact",
            "contacts",
            "contacted",
            "continue",
            "continues",
            "continued",
            "control",
            "controls",
            "controlled",
            "cook",
            "cooks",
            "cooked",
            "copy",
            "copies",
            "copied",
            "cover",
            "covers",
            "covered",
            "create",
            "creates",
            "created",
            "cut",
            "cuts",
            "decide",
            "decides",
            "decided",
            "deliver",
            "delivers",
            "delivered",
            "describe",
            "describes",
            "described",
            "design",
            "designs",
            "designed",
            "destroy",
            "destroys",
            "destroyed",
            "develop",
            "develops",
            "developed",
            "discuss",
            "discusses",
            "discussed",
            "divide",
            "divides",
            "divided",
            "draw",
            "draws",
            "drew",
            "drawn",
            "eat",
            "eats",
            "ate",
            "eaten",
            "elect",
            "elects",
            "elected",
            "employ",
            "employs",
            "employed",
            "encourage",
            "encourages",
            "encouraged",
            "enjoy",
            "enjoys",
            "enjoyed",
            "enter",
            "enters",
            "entered",
            "explain",
            "explains",
            "explained",
            "face",
            "faces",
            "faced",
            "feed",
            "feeds",
            "fed",
            "file",
            "files",
            "filed",
            "fill",
            "fills",
            "filled",
            "fix",
            "fixes",
            "fixed",
            "follow",
            "follows",
            "followed",
            "forget",
            "forgets",
            "forgot",
            "forgotten",
            "forgive",
            "forgives",
            "forgave",
            "forgiven",
            "get",
            "gets",
            "got",
            "gotten",
            "hold",
            "holds",
            "held",
            "improve",
            "improves",
            "improved",
            "include",
            "includes",
            "included",
            "increase",
            "increases",
            "increased",
            "invite",
            "invites",
            "invited",
            "join",
            "joins",
            "joined",
            "keep",
            "keeps",
            "kept",
            "kill",
            "kills",
            "killed",
            "learn",
            "learns",
            "learned",
            "learnt",
            "leave",
            "leaves",
            "left",
            "lend",
            "lends",
            "lent",
            "like",
            "likes",
            "liked",
            "list",
            "lists",
            "listed",
            "lose",
            "loses",
            "lost",
            "measure",
            "measures",
            "measured",
            "meet",
            "meets",
            "met",
            "mention",
            "mentions",
            "mentioned",
            "need",
            "needs",
            "needed",
            "offer",
            "offers",
            "offered",
            "open",
            "opens",
            "opened",
            "order",
            "orders",
            "ordered",
            "paint",
            "paints",
            "painted",
            "pass",
            "passes",
            "passed",
            "pay",
            "pays",
            "paid",
            "pick",
            "picks",
            "picked",
            "place",
            "places",
            "placed",
            "plan",
            "plans",
            "planned",
            "play",
            "plays",
            "played",
            "prefer",
            "prefers",
            "preferred",
            "prepare",
            "prepares",
            "prepared",
            "press",
            "presses",
            "pressed",
            "prove",
            "proves",
            "proved",
            "provide",
            "provides",
            "provided",
            "pull",
            "pulls",
            "pulled",
            "push",
            "pushes",
            "pushed",
            "put",
            "puts",
            "raise",
            "raises",
            "raised",
            "reach",
            "reaches",
            "reached",
            "receive",
            "receives",
            "received",
            "record",
            "records",
            "recorded",
            "remember",
            "remembers",
            "remembered",
            "remove",
            "removes",
            "removed",
            "report",
            "reports",
            "reported",
            "require",
            "requires",
            "required",
            "save",
            "saves",
            "saved",
            "set",
            "sets",
            "shop",
            "shops",
            "shopped",
            "spend",
            "spends",
            "spent",
            "start",
            "starts",
            "started",
            "stop",
            "stops",
            "stopped",
            "study",
            "studies",
            "studied",
            "suggest",
            "suggests",
            "suggested",
            "support",
            "supports",
            "supported",
            "teach",
            "teaches",
            "taught",
            "throw",
            "throws",
            "threw",
            "thrown",
            "try",
            "tries",
            "tried",
            "watch",
            "watches",
            "watched",
            "wear",
            "wears",
            "wore",
            "worn",
            "win",
            "wins",
            "won",
        }
    )

    COMMON_INTRANSITIVE_VERBS: set[str] = frozenset(
        {
            # existing
            "go",
            "goes",
            "went",
            "gone",
            "come",
            "comes",
            "came",
            "run",
            "runs",
            "ran",
            "walk",
            "walks",
            "walked",
            "sit",
            "sits",
            "sat",
            "stand",
            "stands",
            "stood",
            "sleep",
            "sleeps",
            "slept",
            "die",
            "dies",
            "died",
            "arrive",
            "arrives",
            "arrived",
            "sing",
            "sings",
            "sang",
            "sung",
            "jump",
            "jumps",
            "jumped",
            # additions
            "appear",
            "appears",
            "appeared",
            "become",
            "becomes",
            "became",
            "belong",
            "belongs",
            "belonged",
            "collapse",
            "collapses",
            "collapsed",
            "cry",
            "cries",
            "cried",
            "dance",
            "dances",
            "danced",
            "disappear",
            "disappears",
            "disappeared",
            "exist",
            "exists",
            "existed",
            "fall",
            "falls",
            "fell",
            "fallen",
            "happen",
            "happens",
            "happened",
            "laugh",
            "laughs",
            "laughed",
            "live",
            "lives",
            "lived",
            "occur",
            "occurs",
            "occurred",
            "remain",
            "remains",
            "remained",
            "rise",
            "rises",
            "rose",
            "risen",
            "seem",
            "seems",
            "seemed",
            "smile",
            "smiles",
            "smiled",
            "sneeze",
            "sneezes",
            "sneezed",
            "stay",
            "stays",
            "stayed",
            "swim",
            "swims",
            "swam",
            "swum",
            "travel",
            "travels",
            "traveled",
            "wait",
            "waits",
            "waited",
            "work",
            "works",
            "worked",
        }
    )

    # Verbs that take bare infinitives (without 'to') - Rule 25
    BARE_INFINITIVE_VERBS: set[str] = frozenset(
        {
            "bid",
            "bids",
            "bade",
            "bidden",
            "dare",
            "dares",
            "dared",
            "need",
            "needs",
            "needed",
            "make",
            "makes",
            "made",
            "see",
            "sees",
            "saw",
            "seen",
            "hear",
            "hears",
            "heard",
            "feel",
            "feels",
            "felt",
            "help",
            "helps",
            "helped",
            "let",
            "lets",
            # additional causatives/perception verbs that license bare infinitive
            "have",
            "has",
            "had",
            "watch",
            "watches",
            "watched",
            "notice",
            "notices",
            "noticed",
        }
    )

    COMMON_NOUNS: set[str] = frozenset(
        {
            # existing
            "cat",
            "dog",
            "bird",
            "fox",
            "lion",
            "tiger",
            "man",
            "woman",
            "child",
            "person",
            "people",
            "house",
            "home",
            "building",
            "room",
            "door",
            "book",
            "paper",
            "pen",
            "pencil",
            "day",
            "night",
            "morning",
            "evening",
            "time",
            "work",
            "wrong",
            "year",
            "month",
            "week",
            "name",
            "place",
            "thing",
            "world",
            "hand",
            "eye",
            "face",
            "head",
            "city",
            "town",
            "country",
            "state",
            "school",
            "university",
            "college",
            "engineer",
            "teacher",
            "doctor",
            "student",
            "software",
            "hardware",
            "computer",
            # additions (people & relations)
            "parent",
            "mother",
            "father",
            "son",
            "daughter",
            "brother",
            "sister",
            "friend",
            "neighbor",
            "colleague",
            "team",
            "family",
            # places & geography
            "village",
            "region",
            "area",
            "street",
            "road",
            "park",
            "river",
            "mountain",
            "valley",
            "island",
            "office",
            "factory",
            "market",
            "store",
            "shop",
            "bank",
            "hospital",
            "airport",
            # abstract & time
            "idea",
            "issue",
            "matter",
            "reason",
            "result",
            "problem",
            "question",
            "answer",
            "truth",
            "story",
            "history",
            "future",
            "past",
            "present",
            "hour",
            "minute",
            "second",
            "spring",
            "summer",
            "autumn",
            "winter",
            # objects & things
            "car",
            "bus",
            "train",
            "phone",
            "table",
            "chair",
            "window",
            "floor",
            "wall",
            "ceiling",
            "bag",
            "box",
            "cup",
            "glass",
            "bottle",
            "food",
            "water",
            "bread",
            "fruit",
            "vegetable",
            "meat",
            # actions/roles
            "manager",
            "worker",
            "farmer",
            "artist",
            "writer",
            "singer",
            "driver",
            "pilot",
            "nurse",
            "lawyer",
            "judge",
            "police",
            "soldier",
            # misc.
            "language",
            "letter",
            "message",
            "email",
            "music",
            "movie",
            "game",
            "sport",
            "goal",
            "rule",
            "law",
            "policy",
            "tax",
            "price",
            "cost",
            "amount",
            "level",
            "number",
            "figure",
            "data",
            "power",
            "energy",
            "light",
            "sound",
        }
    )

    COMMON_ADJECTIVES: set[str] = frozenset(
        {
            # existing
            "good",
            "bad",
            "big",
            "small",
            "large",
            "little",
            "old",
            "new",
            "young",
            "long",
            "short",
            "hot",
            "cold",
            "warm",
            "cool",
            "quick",
            "slow",
            "fast",
            "lazy",
            "beautiful",
            "ugly",
            "pretty",
            "handsome",
            "happy",
            "sad",
            "angry",
            "glad",
            "red",
            "blue",
            "green",
            "yellow",
            "black",
            "white",
            "brown",
            "interesting",
            "boring",
            "difficult",
            "easy",
            "important",
            "necessary",
            "possible",
            "impossible",
            # additions
            "better",
            "best",
            "worse",
            "worst",
            "early",
            "late",
            "true",
            "false",
            "right",
            "wrong",
            "strong",
            "weak",
            "clean",
            "dirty",
            "full",
            "empty",
            "open",
            "closed",
            "ready",
            "busy",
            "free",
            "public",
            "private",
            "local",
            "national",
            "international",
            "political",
            "social",
            "economic",
            "cultural",
            "general",
            "special",
            "specific",
            "common",
            "rare",
            "fresh",
            "stale",
            "modern",
            "ancient",
            "recent",
            "former",
            "latter",
            "entire",
            "total",
            "mere",
            "own",
            "same",
            "different",
            "next",
            "last",
            "only",
            "whole",
            "clear",
            "dark",
            "bright",
            "quiet",
            "noisy",
            "safe",
            "dangerous",
            "probable",
            "certain",
            "uncertain",
        }
    )

    INTERJECTIONS: set[str] = frozenset(
        {
            "oh",
            "ah",
            "alas",
            "hello",
            "hey",
            "wow",
            "ouch",
            "hurray",
            # additions
            "aha",
            "amen",
            "aw",
            "bravo",
            "cheers",
            "eek",
            "gee",
            "gosh",
            "hmm",
            "huh",
            "jeez",
            "meh",
            "oops",
            "ow",
            "phew",
            "psst",
            "rats",
            "shh",
            "tsk",
            "ugh",
            "whoa",
            "yay",
            "yikes",
            "yippee",
            "zoinks",
        }
    )

    ADVERBS: set[str] = frozenset(
        {
            # existing
            "quickly",
            "slowly",
            "very",
            "much",
            "more",
            "most",
            "still",
            "quite",
            "rather",
            "well",
            "badly",
            "always",
            "never",
            "often",
            "sometimes",
            "here",
            "there",
            "now",
            "then",
            "today",
            "yesterday",
            "tomorrow",
            # additions: time & frequency
            "already",
            "soon",
            "later",
            "early",
            "late",
            "recently",
            "lately",
            "eventually",
            "immediately",
            "instantly",
            "briefly",
            "constantly",
            "frequently",
            "rarely",
            "seldom",
            # degree & manner
            "almost",
            "nearly",
            "hardly",
            "scarcely",
            "barely",
            "simply",
            "truly",
            "clearly",
            "exactly",
            "roughly",
            "approximately",
            "really",
            "extremely",
            "fairly",
            "pretty",
            "highly",
            "incredibly",
            "particularly",
            "completely",
            "entirely",
            "totally",
            "utterly",
            "slightly",
            # stance & probability
            "maybe",
            "perhaps",
            "surely",
            "certainly",
            "probably",
            "possibly",
            "likely",
            "unlikely",
            # place & direction
            "abroad",
            "away",
            "back",
            "forward",
            "together",
            "apart",
            "upstairs",
            "downstairs",
            "inside",
            "outside",
            "nearby",
            "overseas",
            # connective style
            "therefore",
            "however",
            "moreover",
            "furthermore",
            "hence",
            "thus",
        }
    )

    # Instance fields (pluggable lexicons)
    articles: frozenset[str] = field(default_factory=lambda: Lexicon.DEFAULT_ARTICLES)
    personal_pronouns: frozenset[str] = field(
        default_factory=lambda: Lexicon.PERSONAL_PRONOUNS
    )
    possessive_pronouns: frozenset[str] = field(
        default_factory=lambda: Lexicon.POSSESSIVE_PRONOUNS
    )
    demonstrative_pronouns: frozenset[str] = field(
        default_factory=lambda: Lexicon.DEMONSTRATIVE_PRONOUNS
    )
    relative_pronouns: frozenset[str] = field(
        default_factory=lambda: Lexicon.RELATIVE_PRONOUNS
    )
    interrogative_pronouns: frozenset[str] = field(
        default_factory=lambda: Lexicon.INTERROGATIVE_PRONOUNS
    )
    coordinating_conjunctions: frozenset[str] = field(
        default_factory=lambda: Lexicon.COORDINATING_CONJUNCTIONS
    )
    subordinating_conjunctions: frozenset[str] = field(
        default_factory=lambda: Lexicon.SUBORDINATING_CONJUNCTIONS
    )
    prepositions: frozenset[str] = field(default_factory=lambda: Lexicon.PREPOSITIONS)
    auxiliary_be: frozenset[str] = field(default_factory=lambda: Lexicon.AUXILIARY_BE)
    auxiliary_have: frozenset[str] = field(
        default_factory=lambda: Lexicon.AUXILIARY_HAVE
    )
    auxiliary_do: frozenset[str] = field(default_factory=lambda: Lexicon.AUXILIARY_DO)
    auxiliary_get: frozenset[str] = field(default_factory=lambda: Lexicon.AUXILIARY_GET)
    modal_verbs: frozenset[str] = field(default_factory=lambda: Lexicon.MODAL_VERBS)
    transitive_verbs: frozenset[str] = field(
        default_factory=lambda: Lexicon.COMMON_TRANSITIVE_VERBS
    )
    intransitive_verbs: frozenset[str] = field(
        default_factory=lambda: Lexicon.COMMON_INTRANSITIVE_VERBS
    )
    bare_infinitive_verbs: frozenset[str] = field(
        default_factory=lambda: Lexicon.BARE_INFINITIVE_VERBS
    )
    common_nouns: frozenset[str] = field(default_factory=lambda: Lexicon.COMMON_NOUNS)
    common_adjectives: frozenset[str] = field(
        default_factory=lambda: Lexicon.COMMON_ADJECTIVES
    )
    interjections: frozenset[str] = field(default_factory=lambda: Lexicon.INTERJECTIONS)
    adverbs: frozenset[str] = field(default_factory=lambda: Lexicon.ADVERBS)


# Default lexicon instance for backward compatibility
DEFAULT_LEXICON = Lexicon()
